name: Deploy to AWS with OpenTofu

on:
  push:
    branches:
      - main  # Zorg ervoor dat de workflow wordt uitgevoerd bij elke push naar de main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Zorg ervoor dat de job op een Ubuntu runner draait.

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install opentofu

      - name: Add snap binary path to PATH
        run: |
          echo "/snap/bin" >> $GITHUB_PATH  # Zorg ervoor dat de snap binaries in de PATH zitten

      - name: Verify OpenTofu installation
        run: opentofu --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-west-2  # Verander dit naar jouw gewenste regio

      - name: Run OpenTofu init
        run: |
          opentofu init

      - name: Apply OpenTofu configuration
        run: |
          opentofu apply -auto-approve
