name: Deploy to AWS with OpenTofu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS with OpenTofu
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Check out de repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Stap 2: Installeer OpenTofu via Snap
    - name: Setup OpenTofu
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install opentofu --classic
        echo "Snap binaries toegevoegd aan PATH: $(sudo snap install opentofu --classic)"
        export PATH=$PATH:/snap/bin

    # Stap 3: Controleer OpenTofu installatie
    - name: Verify OpenTofu installation
      run: opentofu --version

    # Stap 4: Configureer AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 # Pas dit aan naar jouw regio

    # Stap 5: Initialiseer OpenTofu
    - name: OpenTofu Init
      run: opentofu init

    # Stap 6: Plan OpenTofu
    - name: OpenTofu Plan
      run: opentofu plan -out=tfplan

    # Stap 7: Apply OpenTofu
    - name: OpenTofu Apply
      run: opentofu apply -auto-approve tfplan
