name: Deploy to AWS with OpenTofu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install snapd
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo systemctl enable --now snapd.socket
          sudo snap install opentofu --classic

      - name: Verify snap installation path
        run: |
          echo "Snap bin path: $PATH"  # Debugging de path
          echo "/snap/bin" >> $GITHUB_PATH
          ls /snap/bin  # Bekijk of tofu daar aanwezig is

      - name: Verify OpenTofu installation
        run: |
          which tofu  # Controleer of tofu gevonden kan worden in het pad
          tofu --version  # Bekijk de versie van OpenTofu

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2  # Gebruik de juiste parameter voor regio

      - name: Run OpenTofu init
        run: tofu init

      - name: Apply OpenTofu configuration
        run: |
          tofu apply -auto-approve \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "aws_token=${{ secrets.AWS_SESSION_TOKEN }}"
